### ISSUE TITLE
Replace Array.prototype.indexOf with Array.prototype.findIndex to make replacements case insensitive

### ISSUE THREAD

**Issue by JKirchartz** [JKirchartz/pos2tracery#5]
Replace Array.prototype.indexOf (like on line [49](https://github.com/JKirchartz/pos2tracery/blob/master/index.js#L49) or [53]( https://github.com/JKirchartz/pos2tracery/blob/master/index.js#L53)) with [Array.prototype.findIndex]( https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex) to make replacements case insensitive using [String.prototype.toLowerCase](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toLowerCase)

**Comment by kerlon5** [comment]
Hi, review my PR, please.
